tap "brewforge/extras"
tap "jakehilborn/jakehilborn"
tap "mohamedelashri/free-mac"
tap "nikitabobko/tap"
tap "oven-sh/bun"
tap "sst/tap"
# Run your GitHub Actions locally
brew "act"
# Download with resuming and segmented downloading
brew "aria2"
# Improved shell history for zsh, bash, fish and nushell
brew "atuin"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Console Matrix
brew "cmatrix"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Highest-quality GIF encoder based on pngquant
brew "gifski"
# Distributed revision control system
brew "git"
# Render markdown on the CLI
brew "glow"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Java-based project management
brew "maven"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Manage multiple Node.js versions
brew "nvm"
# Open Fortinet client for PPP+TLS VPN tunnel services
brew "openfortivpn"
# Development kit for the Java programming language
brew "openjdk@21"
# Fast, disk space efficient package manager
brew "pnpm"
# Tool for managing OCI containers and pods
brew "podman"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# SVG rendering tool and library
brew "resvg"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Cross-shell prompt for astronauts
brew "starship"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Code-search similar to ack
brew "the_silver_searcher"
# Official tldr client written in Rust
brew "tlrc"
# Terminal multiplexer
brew "tmux"
# Program that allows you to count code, quickly
brew "tokei"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Incredibly fast JavaScript runtime, bundler, transpiler and package manager - all in one.
brew "oven-sh/bun/bun"
# The AI coding agent built for the terminal.
brew "sst/tap/opencode"
# AeroSpace is an i3-like tiling window manager for macOS
cask "aerospace"
# CPU management application
cask "app-tamer"
# Application uninstaller
cask "appcleaner"
# Compact TeX distribution as alternative to the full TeX Live / MacTeX
cask "basictex"
# App for managing battery charging
cask "batfi"
# Display management tool
cask "betterdisplay"
# Desktop password and login vault
cask "bitwarden"
# Send any size file between devices
cask "blip"
# Open source IDE for exploring and testing APIs
cask "bruno"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# Anthropic's official Claude AI desktop app
cask "claude"
# Image, video and clipboard optimiser
cask "clop"
# Free app that makes your Internet safer
cask "cloudflare-warp"
# Disk space visualiser
cask "daisydisk"
# UI to create reproducible developer environments based on a devcontainer.json
cask "devpod"
cask "font-cascadia-code"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome"
# Free and open-source media player
cask "iina"
# Native desktop app for Messenger (formerly Facebook Messenger)
cask "messenger"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# App to write, plan, collaborate, and get organised
cask "notion"
# Open-source software for live streaming and screen recording
cask "obs"
# Verify system files structure, run miscellaneous maintenance and more
cask "onyx"
# Archive manager for data compression and backups
cask "rar"
# Control your tools with a few keystrokes
cask "raycast"
# System monitor for the menu bar
cask "stats"
# Open-source code editor
cask "visual-studio-code"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
# Native desktop client for WhatsApp
cask "whatsapp"
# Gecko based web browser
cask "zen"
vscode "adpyke.codesnap"
vscode "alefragnani.bookmarks"
vscode "angular.ng-template"
vscode "eamodio.gitlens"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "mads-hartmann.bash-ide-vscode"
vscode "ms-azuretools.vscode-containers"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "nrwl.angular-console"
vscode "tal7aouy.icons"
vscode "webhooked.kanso-theme"
vscode "yinfei.luahelper"
vscode "yoavbls.pretty-ts-errors"
