vim.cmd("highlight clear")
vim.o.termguicolors = true
vim.g.colors_name = "github_dark_dimmed_custom"

local set = vim.api.nvim_set_hl

-- Base
set(0, "Normal",        { fg = "#d1d7e0", bg = "#212830" })
set(0, "NormalFloat",   { fg = "#d1d7e0", bg = "#151b23" })
set(0, "CursorLine",    { bg = "#262c36" })
set(0, "LineNr",        { fg = "#9198a1" })
set(0, "CursorLineNr",  { fg = "#d1d7e0" })
set(0, "SignColumn",    { bg = "#212830" })
set(0, "ColorColumn",   { bg = "#262c36" })
set(0, "EndOfBuffer",   { fg = "#3d444d" })

-- UI
set(0, "Visual",        { bg = "#316dca", fg = "#f0f6fc" })
set(0, "Search",        { bg = "#c69026", fg = "#212830" })
set(0, "IncSearch",     { bg = "#eac55f", fg = "#212830" })
set(0, "StatusLine",    { bg = "#151b23", fg = "#d1d7e0" })
set(0, "StatusLineNC",  { bg = "#151b23", fg = "#9198a1" })
set(0, "VertSplit",     { fg = "#3d444d" })
set(0, "WinSeparator",  { fg = "#3d444d" })
set(0, "TabLine",       { bg = "#151b23", fg = "#9198a1" })
set(0, "TabLineSel",    { bg = "#212830", fg = "#d1d7e0" })
set(0, "TabLineFill",   { bg = "#151b23" })
set(0, "Pmenu",         { bg = "#262c36", fg = "#d1d7e0" })
set(0, "PmenuSel",      { bg = "#316dca", fg = "#f0f6fc" })
set(0, "PmenuSbar",     { bg = "#3d444d" })
set(0, "PmenuThumb",    { bg = "#656c76" })
set(0, "FloatBorder",   { fg = "#3d444d", bg = "#151b23" })

-- Syntax
set(0, "Comment",       { fg = "#9198a1", italic = true })
set(0, "String",        { fg = "#96d0ff" })
set(0, "Number",        { fg = "#6cb6ff" })
set(0, "Float",         { fg = "#6cb6ff" })
set(0, "Boolean",       { fg = "#6cb6ff" })
set(0, "Character",     { fg = "#96d0ff" })
set(0, "Function",      { fg = "#dcbdfb" })
set(0, "Identifier",    { fg = "#d1d7e0" })
set(0, "Keyword",       { fg = "#f47067" })
set(0, "Conditional",   { fg = "#f47067" })
set(0, "Repeat",        { fg = "#f47067" })
set(0, "Operator",      { fg = "#f47067" })
set(0, "Type",          { fg = "#f69d50" })
set(0, "StorageClass",  { fg = "#f47067" })
set(0, "Constant",      { fg = "#6cb6ff" })
set(0, "PreProc",       { fg = "#f47067" })
set(0, "Special",       { fg = "#f47067" })
set(0, "Statement",     { fg = "#f47067" })
set(0, "Title",         { fg = "#6cb6ff", bold = true })
set(0, "Todo",          { fg = "#212830", bg = "#eac55f", bold = true })
set(0, "Error",         { fg = "#e5534b" })
set(0, "Underlined",    { underline = true })

-- Treesitter
set(0, "@variable",              { fg = "#d1d7e0" })
set(0, "@variable.builtin",      { fg = "#6cb6ff" })
set(0, "@variable.parameter",    { fg = "#f69d50" })
set(0, "@function",              { fg = "#dcbdfb" })
set(0, "@function.builtin",      { fg = "#dcbdfb" })
set(0, "@function.call",         { fg = "#dcbdfb" })
set(0, "@method",                { fg = "#dcbdfb" })
set(0, "@method.call",           { fg = "#dcbdfb" })
set(0, "@keyword",               { fg = "#f47067" })
set(0, "@keyword.function",      { fg = "#f47067" })
set(0, "@keyword.return",        { fg = "#f47067" })
set(0, "@keyword.operator",      { fg = "#f47067" })
set(0, "@type",                  { fg = "#f69d50" })
set(0, "@type.builtin",          { fg = "#6cb6ff" })
set(0, "@string",                { fg = "#96d0ff" })
set(0, "@string.escape",         { fg = "#f47067" })
set(0, "@number",                { fg = "#6cb6ff" })
set(0, "@boolean",               { fg = "#6cb6ff" })
set(0, "@operator",              { fg = "#f47067" })
set(0, "@punctuation.bracket",   { fg = "#d1d7e0" })
set(0, "@punctuation.delimiter", { fg = "#d1d7e0" })
set(0, "@comment",               { fg = "#9198a1", italic = true })
set(0, "@property",              { fg = "#d1d7e0" })
set(0, "@field",                 { fg = "#d1d7e0" })
set(0, "@tag",                   { fg = "#8ddb8c" })
set(0, "@tag.attribute",         { fg = "#6cb6ff" })
set(0, "@tag.delimiter",         { fg = "#9198a1" })
set(0, "@attribute",             { fg = "#6cb6ff" })
set(0, "@constructor",           { fg = "#f47067" })
set(0, "@string.special",        { fg = "#6cb6ff" })
set(0, "@label",                 { fg = "#6cb6ff" })
set(0, "@punctuation.special",   { fg = "#f47067" })
set(0, "@text.emphasis",         { italic = true })
set(0, "@text.strong",           { bold = true })
set(0, "@text.literal",          { fg = "#6cb6ff" })
set(0, "@text.uri",              { fg = "#6cb6ff" })
set(0, "@text.reference",        { fg = "#96d0ff", italic = true })
set(0, "@lsp.type.enum",         { fg = "#f69d50" })
set(0, "@variable.member",       { fg = "#8ddb8c" })  -- json keys / property.json_key

-- Diff
set(0, "DiffAdd",       { bg = "#1b4721" })
set(0, "DiffChange",    { bg = "#2a2415" })
set(0, "DiffDelete",    { bg = "#3c1a1a" })
set(0, "DiffText",      { bg = "#4a3800" })
set(0, "Added",         { fg = "#46954a" })
set(0, "Changed",       { fg = "#c69026" })
set(0, "Removed",       { fg = "#e5534b" })

-- Diagnostics
set(0, "DiagnosticError",          { fg = "#e5534b" })
set(0, "DiagnosticWarn",           { fg = "#c69026" })
set(0, "DiagnosticInfo",           { fg = "#539bf5" })
set(0, "DiagnosticHint",           { fg = "#9198a1" })
set(0, "DiagnosticUnderlineError", { undercurl = true, sp = "#e5534b" })
set(0, "DiagnosticUnderlineWarn",  { undercurl = true, sp = "#c69026" })
set(0, "DiagnosticUnderlineInfo",  { undercurl = true, sp = "#539bf5" })
set(0, "DiagnosticUnderlineHint",  { undercurl = true, sp = "#9198a1" })

-- Git signs
set(0, "GitSignsAdd",    { fg = "#46954a" })
set(0, "GitSignsChange", { fg = "#c69026" })
set(0, "GitSignsDelete", { fg = "#e5534b" })
