nerdfont: true
files:
  symlink:
    - node_modules
    - "apps/*/node_modules"
    - "packages/*/node_modules"
    - "libs/*/node_modules"
    - "services/*/node_modules"
  copy:
    - .env
    - "apps/*/.env"
    - "packages/*/.env"
    - "libs/*/.env"
    - "services/*/.env"
